services:
  audit-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}

    container_name: hospital-audit-service
    ports:
      - '9002:9002'
    environment:
      NODE_ENV: development
      PORT: 9002

      # Database
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: 'Iwuhkel12#'
      DB_NAME: hospital_audit_db

      # CONNECT TO EXISTING RABBITMQ FROM MAIN SERVICE
      RABBITMQ_URL: amqp://guest:guest@hospital-rabbitmq:5672

      # Gateway secret
      GATEWAY_SECRET: super-secret-dev-key

      AUTH_GRPC_URL: auth-service:50051

      REDIS_HOST: hospital-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:

    volumes:
      - ./audit-service:/usr/src/app
      - /usr/src/app/node_modules

    command: yarn start:dev

    networks:
      - hospital-network

networks:
  hospital-network:
    external: true
    name: hospital-network
